language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-toy' ]; then cd .. && eval "mv $currentfolder generator-toy" && cd generator-toy; fi

